[package]
name = "athena"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tokio = { version = "1", features = ["full"] }
maud = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
markdown = "0.3.0"
regex = "1.10.6"
yaml-rust = "0.4.5"
